extensions:
  basicauth:
    client_auth:
      username: admin
      password: admin

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  otlphttp:
    endpoint: "http://data-prepper:21891/otel/v1/metrics"
    tls:
      insecure: true

service:
  extensions: [basicauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]