extensions:
  oauth2client/client:
    client_id: agent 
    client_secret: NShYiPHKGwrOEOlu8bWbhDiyxOazBCLp
    token_url: http://0.0.0.0:8080/realms/opentelemetry/protocol/openid-connect/token

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:5317

exporters:
  otlp/secure:
    endpoint: localhost:4317
    tls:
      ca_file: ca.pem
      cert_file: client.pem
      key_file: client-key.pem
    auth:
      authenticator: oauth2client/client

service:
  extensions: [oauth2client/client]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlp/secure]