extensions:
  oidc:
    issuer_url: http://localhost:8080/realms/opentelemetry
    issuer_ca_path: /etc/server.pem
    audience: collector
    attribute: authorization

receivers:
  otlp/secure:
    protocols:
      grpc:
        auth:
          authenticator: oidc
        tls:
          cert_file: ./server.pem
          key_file: ./server-key.pem

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  extensions: [oidc]
  pipelines:
    metrics:
      receivers: [otlp/secure]
      processors: [batch]
      exporters: [prometheus]
